### ISSUE TITLE
Verifikace akce

### ISSUE THREAD

**Issue by jakubzika** [MakersLab/farm-client#9]
Asi by bylo dobrý přidat něco co se zeptá před tím než provedeš akci s tiskárnou. Nechceš omylem vypnout tisk na několika tiskárnách.

**Comment by Houba28** [comment]
souhlas

**Comment by Houba28** [comment]
edit: tlačítko ŸES a No by bylo lepší prohodit, je to nezvykle obráceně, podle Mašiny :D
